set(MBED_LOCATION "/home/alax/git/mbed-os/BUILD/mbed")

link_directories("${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TOOLCHAIN_GCC_ARM/")

file(GLOB hal "${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TOOLCHAIN_GCC_ARM/*.o")

add_library(mbed_library INTERFACE)
add_library(mbed::mbed ALIAS mbed_library)

target_sources(mbed_library INTERFACE ${hal})


target_include_directories(mbed_library
	 INTERFACE
		"${MBED_LOCATION}"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM/TARGET_STM32F4/"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM/TARGET_STM32F4/device"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM"
		"${MBED_LOCATION}/TARGET_NUCLEO_F411RE/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/"
		"${MBED_LOCATION}/platform"
		"${MBED_LOCATION}/hal"
)

target_link_libraries(mbed_library
	INTERFACE
		mbed
)



set(CMAKE_MODULE_PATH "${PROJECT_ROOT_DIR}")






